# Generated by Django 4.0.4 on 2022-04-12 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='Owner',
            new_name='owner',
        ),
        migrations.AlterModelTable(
            name='dog',
            table='dogs',
        ),
    ]
